POST http://localhost:3001/api/persons
Content-Type: application/json

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "55555"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "55555"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "55555"
}